---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/groups":
    get:
      summary: list classes
      tags:
      - Classes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      responses:
        '200':
          description: successful
    post:
      summary: Creates a class
      tags:
      - Classes
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      - name: class
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: text
            rating:
              type: integer
            image:
              type: string
            title:
              type: string
            user_id:
              type: integer
          required:
          - name
          - description
          - rating
          - image
          - title
          - user_id
      responses:
        '201':
          description: Creates class
  "/groups/{id}":
    get:
      summary: Get class details
      tags:
      - Classes
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Created
  "/reservations":
    get:
      summary: List Reservations
      tags:
      - Reservations
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      responses:
        '200':
          description: Success
    post:
      summary: Creates reservation
      tags:
      - Reservations
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      - name: reservation
        in: body
        schema:
          type: object
          properties:
            date:
              type: string
              format: datetime
            group_id:
              type: integer
            user_id:
              type: integer
            city:
              type: string
          required:
          - date
          - group_id
      responses:
        '201':
          description: reservation created
  "/reservations/{id}":
    delete:
      summary: Deletes a reservation
      tags:
      - Reservation
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: Success
  "/registrations":
    post:
      summary: Creates a user
      tags:
      - Users
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            password:
              type: string
          required:
          - name
          - email
          - password
      responses:
        '201':
          description: Created
  "/sessions":
    post:
      summary: logs in an existing user
      tags:
      - Users
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: Success
  "/logout":
    delete:
      summary: resets session
      tags:
      - Users
      consumes:
      - application/json
      produces:
      - application/json
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
        description: Client token
      - name: id
        in: path
        type: integer
        required: true
      responses:
        '200':
          description: success
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: https://url.com/